### PR TITLE
Add error-on-found when object found

### PR DESCRIPTION
**Pull request by rikatz**
Signed-off-by: Ricardo Pchevuzinske Katz <ricardo.katz@gmail.com>

Add the flag ``--error-on-deprecated`` and ``error-on-deleted`` that exists Pug with an error when objects of a deprecated or deleted apis are found.

Fixes: #67

### CODE REVIEW

**Comment by rikatz** [comment]
@grosser PTAL, the behavior here is IF there are  deprecated (not removed yet) or deleted (removed, breaking change) objects, and --error-on-found the program will exit with status code 1.

Sounds good?

**Comment by grosser** [comment]
by default: error on removed <-> because it blocks updates
with `--error-on-deprecated`: error when only deprecated <-> because you need to update to get into the deprecated state first 🤷

**Comment by rikatz** [comment]
Great :) 

I just don't think that making this a default behavior now would be good, as there might be some people using and already relying on it exiting with code 0 :)

**Comment by rikatz** [comment]
Changed to --error-on-deprecated and --error-on-deleted, both defaults to false.

**Comment by grosser** [comment]
sounds safe, thx

**Pull request merged**
